plugins {
    id 'java'
    id 'net.neoforged.moddev' version '2.0.78'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

neoForge {
    version = project.neo_version
}

repositories {
    mavenCentral()
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = 'UTF-8'
    it.options.release = 21
}

processResources {
    def expandProps = [
            'version'          : project.mod_version,
            'minecraft_version': project.minecraft_version,
            'neo_version'      : project.neo_version
    ]
    inputs.properties(expandProps)
    filesMatching(['META-INF/neoforge.mods.toml', 'pack.mcmeta']) {
        expand expandProps
    }
}
